version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: resume_matcher
      # Remove MYSQL_USER since it's not allowed for the root user.
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:password@db/resume_matcher"
      SQLALCHEMY_TRACK_MODIFICATIONS: "False"
      AWS_SES_REGION: "us-east-1"
      AWS_SES_SENDER: "your-email@example.com"
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frountend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
